require 'rails_helper'

RSpec.describe "User can create an account" do
    it "selects the option to create an account" do
      visit '/users'

      click_link("Create an account")

      fill_in('First name', with: 'Edilene')
      fill_in('Last name', with: 'Stormy')
      fill_in('Username', with: 'perfectstorm')
      fill_in('Password', with: 'password')
      click_button('Create account')

      expect(page).to have_content("Welcome, Edilene!")
  end
end


# user can create an account
# user can login
# can be authenticated
# can logout

#
# an admin visits the root
# login recognized as admin access
# choose the option to create a gif
# type in search/create field one-word that will bring an image
# image is generated by
# gif should have an image path
# this will bring admin to page that displays all gifs created
